package com.siap.rasi.pojo;
// Generated 4/08/2016 04:32:58 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * SolicitudInformacion generated by hbm2java
 */
public class SolicitudInformacion implements java.io.Serializable {

    private long id;
    private Date fecha;
    private String nombres;
    private String apellidoPaterno;
    private String apellidoMaterno;
    private String ocupacion;
    private String entidadFederativa;
    private String institucion;
    private String telefonoFijo;
    private String telefonoCelular;
    private String correo;
    private String tipoInformacion;
    private String especifiqueInformacion;
    private String viaSolicitud;
    private boolean recibirInformacion;
    private Date fechaAtencion;
    private String atendioSolicitud;

    public SolicitudInformacion() {
    }

    public SolicitudInformacion(long id, Date fecha, String nombres, String apellidoPaterno, String apellidoMaterno, String ocupacion, String entidadFederativa, String institucion, String telefonoFijo, String telefonoCelular, String correo, String tipoInformacion, String especifiqueInformacion, String viaSolicitud, boolean recibirInformacion) {
        this.id = id;
        this.fecha = fecha;
        this.nombres = nombres;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.ocupacion = ocupacion;
        this.entidadFederativa = entidadFederativa;
        this.institucion = institucion;
        this.telefonoFijo = telefonoFijo;
        this.telefonoCelular = telefonoCelular;
        this.correo = correo;
        this.tipoInformacion = tipoInformacion;
        this.especifiqueInformacion = especifiqueInformacion;
        this.viaSolicitud = viaSolicitud;
        this.recibirInformacion = recibirInformacion;
    }

    public SolicitudInformacion(long id, Date fecha, String nombres, String apellidoPaterno, String apellidoMaterno, String ocupacion, String entidadFederativa, String institucion, String telefonoFijo, String telefonoCelular, String correo, String tipoInformacion, String especifiqueInformacion, String viaSolicitud, boolean recibirInformacion, Date fechaAtencion, String atendioSolicitud) {
        this.id = id;
        this.fecha = fecha;
        this.nombres = nombres;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.ocupacion = ocupacion;
        this.entidadFederativa = entidadFederativa;
        this.institucion = institucion;
        this.telefonoFijo = telefonoFijo;
        this.telefonoCelular = telefonoCelular;
        this.correo = correo;
        this.tipoInformacion = tipoInformacion;
        this.especifiqueInformacion = especifiqueInformacion;
        this.viaSolicitud = viaSolicitud;
        this.recibirInformacion = recibirInformacion;
        this.fechaAtencion = fechaAtencion;
        this.atendioSolicitud = atendioSolicitud;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }

    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }

    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    public String getOcupacion() {
        return this.ocupacion;
    }

    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }

    public String getEntidadFederativa() {
        return this.entidadFederativa;
    }

    public void setEntidadFederativa(String entidadFederativa) {
        this.entidadFederativa = entidadFederativa;
    }

    public String getInstitucion() {
        return this.institucion;
    }

    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }

    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }

    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }

    public String getTelefonoCelular() {
        return this.telefonoCelular;
    }

    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }

    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getTipoInformacion() {
        return this.tipoInformacion;
    }

    public void setTipoInformacion(String tipoInformacion) {
        this.tipoInformacion = tipoInformacion;
    }

    public String getEspecifiqueInformacion() {
        return this.especifiqueInformacion;
    }

    public void setEspecifiqueInformacion(String especifiqueInformacion) {
        this.especifiqueInformacion = especifiqueInformacion;
    }

    public String getViaSolicitud() {
        return this.viaSolicitud;
    }

    public void setViaSolicitud(String viaSolicitud) {
        this.viaSolicitud = viaSolicitud;
    }

    public boolean isRecibirInformacion() {
        return this.recibirInformacion;
    }

    public void setRecibirInformacion(boolean recibirInformacion) {
        this.recibirInformacion = recibirInformacion;
    }

    public Date getFechaAtencion() {
        return this.fechaAtencion;
    }

    public void setFechaAtencion(Date fechaAtencion) {
        this.fechaAtencion = fechaAtencion;
    }

    public String getAtendioSolicitud() {
        return this.atendioSolicitud;
    }

    public void setAtendioSolicitud(String atendioSolicitud) {
        this.atendioSolicitud = atendioSolicitud;
    }

    @Override
    public String toString() {
        return this.fecha.toString() + ", " + this.nombres; //To change body of generated methods, choose Tools | Templates.
    }

}
