package com.siap.rasi.pojo;
// Generated 19/08/2016 03:56:54 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * SolicitudInformacion generated by hbm2java
 */
public class SolicitudInformacion implements java.io.Serializable {

    private long id;
    private Usuario usuario;
    private UsuarioSolicitud usuarioSolicitud;
    private Date fecha;
    private String tipoInformacion;
    private String especifiqueInformacion;
    private String viaSolicitud;
    private Date fechaAtencion;
    private String atendioSolicitud;


    public SolicitudInformacion() {
    }

    public SolicitudInformacion(long id, Usuario usuario, UsuarioSolicitud usuarioSolicitud, Date fecha, String tipoInformacion, String especifiqueInformacion, String viaSolicitud) {
        this.id = id;
        this.usuario = usuario;
        this.usuarioSolicitud = usuarioSolicitud;
        this.fecha = fecha;
        this.tipoInformacion = tipoInformacion;
        this.especifiqueInformacion = especifiqueInformacion;
        this.viaSolicitud = viaSolicitud;
    }

    public SolicitudInformacion(long id, Usuario usuario, UsuarioSolicitud usuarioSolicitud, Date fecha, String tipoInformacion, String especifiqueInformacion, String viaSolicitud, Date fechaAtencion, String atendioSolicitud) {
        this.id = id;
        this.usuario = usuario;
        this.usuarioSolicitud = usuarioSolicitud;
        this.fecha = fecha;
        this.tipoInformacion = tipoInformacion;
        this.especifiqueInformacion = especifiqueInformacion;
        this.viaSolicitud = viaSolicitud;
        this.fechaAtencion = fechaAtencion;
        this.atendioSolicitud = atendioSolicitud;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public UsuarioSolicitud getUsuarioSolicitud() {
        return this.usuarioSolicitud;
    }

    public void setUsuarioSolicitud(UsuarioSolicitud usuarioSolicitud) {
        this.usuarioSolicitud = usuarioSolicitud;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getTipoInformacion() {
        return this.tipoInformacion;
    }

    public void setTipoInformacion(String tipoInformacion) {
        this.tipoInformacion = tipoInformacion;
    }

    public String getEspecifiqueInformacion() {
        return this.especifiqueInformacion;
    }

    public void setEspecifiqueInformacion(String especifiqueInformacion) {
        this.especifiqueInformacion = especifiqueInformacion;
    }

    public String getViaSolicitud() {
        return this.viaSolicitud;
    }

    public void setViaSolicitud(String viaSolicitud) {
        this.viaSolicitud = viaSolicitud;
    }

    public Date getFechaAtencion() {
        return this.fechaAtencion;
    }

    public void setFechaAtencion(Date fechaAtencion) {
        this.fechaAtencion = fechaAtencion;
    }

    public String getAtendioSolicitud() {
        return this.atendioSolicitud;
    }

    public void setAtendioSolicitud(String atendioSolicitud) {
        this.atendioSolicitud = atendioSolicitud;
    }

}
