package com.siap.rasi.pojo;
// Generated 19/08/2016 03:56:54 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * SolicitudInformacion generated by hbm2java
 */
public class SolicitudInformacion implements java.io.Serializable {

    private Long id;
    private Date fecha;
    private String tipoInformacion;
    private String especifiqueInformacion;
    private String viaSolicitud;
    private Date fechaAtencion;
    private String atendioSolicitud;
    private String username;
    private Long idUsuarioSolicitud;

    public SolicitudInformacion() {
    }

    /**
     *
     * @param fecha
     * @param tipoInformacion
     * @param especifiqueInformacion
     * @param viaSolicitud
     * @param idUsuarioSolicitud
     * @param username
     */
    public SolicitudInformacion(Date fecha, String tipoInformacion, String especifiqueInformacion, String viaSolicitud, long idUsuarioSolicitud, String username) {
        this.username = username;
        this.idUsuarioSolicitud = idUsuarioSolicitud;
        this.fecha = fecha;
        this.tipoInformacion = tipoInformacion;
        this.especifiqueInformacion = especifiqueInformacion;
        this.viaSolicitud = viaSolicitud;
    }

    /**
     *
     * @param id
     * @param fecha
     * @param tipoInformacion
     * @param especifiqueInformacion
     * @param viaSolicitud
     * @param fechaAtencion
     * @param atendioSolicitud
     * @param idUsuarioSolicitud
     * @param username
     */
    public SolicitudInformacion(Long id, Date fecha, String tipoInformacion, String especifiqueInformacion, String viaSolicitud, Date fechaAtencion, String atendioSolicitud, long idUsuarioSolicitud, String username) {
        this.id = id;
        this.username = username;
        this.idUsuarioSolicitud = idUsuarioSolicitud;
        this.fecha = fecha;
        this.tipoInformacion = tipoInformacion;
        this.especifiqueInformacion = especifiqueInformacion;
        this.viaSolicitud = viaSolicitud;
        this.fechaAtencion = fechaAtencion;
        this.atendioSolicitud = atendioSolicitud;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Long getIdUsuarioSolicitud() {
        return this.idUsuarioSolicitud;
    }

    public void setUsuarioSolicitud(Long idUsuarioSolicitud) {
        this.idUsuarioSolicitud = idUsuarioSolicitud;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getTipoInformacion() {
        return this.tipoInformacion;
    }

    public void setTipoInformacion(String tipoInformacion) {
        this.tipoInformacion = tipoInformacion;
    }

    public String getEspecifiqueInformacion() {
        return this.especifiqueInformacion;
    }

    public void setEspecifiqueInformacion(String especifiqueInformacion) {
        this.especifiqueInformacion = especifiqueInformacion;
    }

    public String getViaSolicitud() {
        return this.viaSolicitud;
    }

    public void setViaSolicitud(String viaSolicitud) {
        this.viaSolicitud = viaSolicitud;
    }

    public Date getFechaAtencion() {
        return this.fechaAtencion;
    }

    public void setFechaAtencion(Date fechaAtencion) {
        this.fechaAtencion = fechaAtencion;
    }

    public String getAtendioSolicitud() {
        return this.atendioSolicitud;
    }

    public void setAtendioSolicitud(String atendioSolicitud) {
        this.atendioSolicitud = atendioSolicitud;
    }

    @Override
    public String toString() {
        return this.id
                + "," + this.fecha
                + "," + this.tipoInformacion
                + "," + this.especifiqueInformacion
                + "," + this.viaSolicitud
                + "," + this.fechaAtencion
                + "," + this.atendioSolicitud
                + "," + this.idUsuarioSolicitud
                + "," + this.username; //To change body of generated methods, choose Tools | Templates.
    }

}
