package com.siap.rasi.pojo;
// Generated 19/08/2016 03:56:54 PM by Hibernate Tools 4.3.1



/**
 * TipoInformacion generated by hbm2java
 */
public class TipoInformacion  implements java.io.Serializable {


     private long id;
     private String nombre;
     private String descripcion;

    public TipoInformacion() {
    }

	
    public TipoInformacion(long id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public TipoInformacion(long id, String nombre, String descripcion) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


