package com.siap.rasi.pojo;
// Generated 19/08/2016 03:56:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String username;
     private String password;
     private Boolean activo;
     private Set<UsuarioSolicitud> usuarioSolicituds = new HashSet<UsuarioSolicitud>(0);
     private Set<SolicitudInformacion> solicitudInformacions = new HashSet<SolicitudInformacion>(0);

    public Usuario() {
    }

	
    public Usuario(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public Usuario(String username, String password, Boolean activo, Set<UsuarioSolicitud> usuarioSolicituds, Set<SolicitudInformacion> solicitudInformacions) {
       this.username = username;
       this.password = password;
       this.activo = activo;
       this.usuarioSolicituds = usuarioSolicituds;
       this.solicitudInformacions = solicitudInformacions;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Set<UsuarioSolicitud> getUsuarioSolicituds() {
        return this.usuarioSolicituds;
    }
    
    public void setUsuarioSolicituds(Set<UsuarioSolicitud> usuarioSolicituds) {
        this.usuarioSolicituds = usuarioSolicituds;
    }
    public Set<SolicitudInformacion> getSolicitudInformacions() {
        return this.solicitudInformacions;
    }
    
    public void setSolicitudInformacions(Set<SolicitudInformacion> solicitudInformacions) {
        this.solicitudInformacions = solicitudInformacions;
    }




}


