package com.siap.rasi.pojo;
// Generated 19/08/2016 03:56:54 PM by Hibernate Tools 4.3.1

/**
 * UsuarioSolicitud generated by hbm2java
 */
public class UsuarioSolicitud implements java.io.Serializable {

    private Long id;
    private Usuario usuario;
    private String nombres;
    private String apellidoPaterno;
    private String apellidoMaterno;
    private String sexo;
    private String ocupacion;
    private String pais;
    private String correo;
    private boolean recibirInformacion;
    private String telefonoCelular;
    private String telefonoFijo;
    private String institucion;
    private String entidadFederativa;

    public UsuarioSolicitud() {
    }

    public UsuarioSolicitud(Long id, String nombres, String apellidoPaterno, String apellidoMaterno, String sexo, String ocupacion, String pais, String correo, String telefonoCelular, String telefonoFijo, String institucion) {
        this.id = id;
        this.nombres = nombres;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.sexo = sexo;
        this.ocupacion = ocupacion;
        this.pais = pais;
        this.correo = correo;
        this.telefonoCelular = telefonoCelular;
        this.telefonoFijo = telefonoFijo;
        this.institucion = institucion;
    }

    public UsuarioSolicitud(Long id, Usuario usuario, String nombres, String apellidoPaterno, String apellidoMaterno, String sexo, String ocupacion, String pais, String correo, String telefonoCelular, String telefonoFijo, String institucion, String entidadFederativa, boolean recibirInformacion) {
        this.id = id;
        this.usuario = usuario;
        this.nombres = nombres;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.sexo = sexo;
        this.ocupacion = ocupacion;
        this.pais = pais;
        this.correo = correo;
        this.telefonoCelular = telefonoCelular;
        this.telefonoFijo = telefonoFijo;
        this.institucion = institucion;
        this.entidadFederativa = entidadFederativa;
        this.recibirInformacion = recibirInformacion;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }

    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }

    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    public String getSexo() {
        return this.sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public String getOcupacion() {
        return this.ocupacion;
    }

    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }

    public String getPais() {
        return this.pais;
    }

    public void setPais(String pais) {
        this.pais = pais;
    }

    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public boolean isRecibirInformacion() {
        return recibirInformacion;
    }

    public void setRecibirInformacion(boolean recibirInformacion) {
        this.recibirInformacion = recibirInformacion;
    }

    public String getTelefonoCelular() {
        return this.telefonoCelular;
    }

    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }

    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }

    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }

    public String getInstitucion() {
        return this.institucion;
    }

    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }

    public String getEntidadFederativa() {
        return this.entidadFederativa;
    }

    public void setEntidadFederativa(String entidadFederativa) {
        this.entidadFederativa = entidadFederativa;
    }

}
